---
- hosts: dev
  become: True
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Start the container
      shell : |
	docker run -itd --name swapgops1 -p 8081:8080 swapgops/webapp:${{DOCKER_TAG}}
